---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  MultiAZ:
    Description: Multi-AZ master database
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    ConstraintDescription: must be true or false.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - Stage
      - Label:
          default: Network Configuration
        Parameters:
          - VPCCidrBlock
      - Label:
          default: Compute Configuration
        Parameters:
          - KeyName
          - InstanceType
    ParameterLabels:
      Stage:
        default: Stage
      VPCCidrBlock:
        default: VPC Cidr Block
      KeyName:
        default: Key Name
      InstanceType:
        default: Instance Type

Resources:
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/rds.yml
      Parameters:
        DBName: !Ref DBName
        DBUser: !Ref DBUser
        MultiAZ: !Ref MultiAZ
    DependsOn: VPC
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/ecs.yml
    DependsOn: VPC
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/vpc.yml