---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Stage:
    Type: String
    Default: dev
  VPCCidrBlock:
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - Stage
      - Label:
          default: Network Configuration
        Parameters:
          - VPCCidrBlock
      - Label:
          default: Compute Configuration
        Parameters:
          - KeyName
          - InstanceType
    ParameterLabels:
      Stage:
        default: Stage
      VPCCidrBlock:
        default: VPC Cidr Block
      KeyName:
        default: Key Name
      InstanceType:
        default: Instance Type

Resources:
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/rds.yml
      Parametes:
        Subnets: 'subnet-37ac516f\,subnet-94f72ce2'
        SourceSecurityGroup: sg-04ce930d54d7241df
        VPC: vpc-cecea5aa
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/ecs.yml
      Parameters:
        DBName: itizen
        DBUser: itizen
        DBPassword: itizen_rds_password
        EC2SecurityGroup: sg-04ce930d54d7241df
        MultiAZ: true
        VPC: vpc-cecea5aa
        Subnets: 'subnet-37ac516f\,subnet-94f72ce2'