AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Parameters:
  StackID:
    Type: String
  RDSSnapshotID:
    Type: String
  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  MultiAZ:
    Description: Multi-AZ master database
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    ConstraintDescription: must be true or false.
  DNSHostedZone:
    Description: Domain name
    Type: String
    Default: "kter.jp."
  DNSDomain:
    Description: Domain name
    Type: String
    Default: "kter.jp"
Resources:
  # ここでSecurity Groupを設定しないのはSourceSecurityGroupIdに別スタックのSecurity Groupを設定する必要があるため
  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "DB SubnetGroup for itizen"
      SubnetIds:
        - Fn::ImportValue:
            !Sub "${StackID}-Subnet1"
        - Fn::ImportValue:
            !Sub "${StackID}-Subnet2"
  MasterDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSnapshotIdentifier: !Ref RDSSnapshotID
      DBName: !Ref 'DBName'
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: !Ref 'DBUser'
      MasterUserPassword: '{{resolve:ssm-secure:itizen_rds_password_sec:1}}'
      MultiAZ: !Ref 'MultiAZ'
      Tags:
      - Key: Name
        Value: Master Database
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Sub "${StackID}-DBEC2SecurityGroupId"
      DBSubnetGroupName: !Ref DBSubnetGroup
    DeletionPolicy: Snapshot
  FrontDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref DNSHostedZone
      Name: !Join
        - ''
        - - 'db'
          - '.'
          - 'itizen'
          - '.'
          - !Ref DNSHostedZone
      Type: CNAME
      TTL: '60'
      ResourceRecords:
      - !GetAtt MasterDB.Endpoint.Address